/* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>

int fibonacci(int term);

int main(void) 
{
	int i = 0;
	int term = 0;
	double sum;

	do {
		i++;
		term = fibonacci(i);
		if (term % 2 == 0) {
			sum += term;
		}		
	} while (term < 4000000);
	printf("The sum is %f\n", sum);
}

int fibonacci(term)
{
	if (term == 1)
		return 1;
	else if (term == 2)
		return 2;
	else
		return fibonacci(term - 1) + fibonacci(term - 2);
}
